using System.Text;
using src.RiwiLens.Application.DTOs.Cv;
using src.RiwiLens.Application.Interfaces.Repositories;
using src.RiwiLens.Application.Interfaces.Services;
using src.RiwiLens.Domain.Entities;

namespace src.RiwiLens.Application.Services;

public class CvService : ICvService
{
    private readonly IGenericRepository<Coder> _coderRepo;
    private readonly IGenericRepository<CoderTechnicalSkill> _coderTechSkillRepo;
    private readonly IGenericRepository<TechnicalSkill> _techSkillRepo;
    private readonly IGenericRepository<CoderSoftSkill> _coderSoftSkillRepo;
    private readonly IGenericRepository<SoftSkill> _softSkillRepo;
    private readonly IGenericRepository<ProfessionalProfile> _profileRepo;
    private readonly IGenericRepository<ClanCoder> _clanCoderRepo;
    private readonly IGenericRepository<Clan> _clanRepo;

    public CvService(
        IGenericRepository<Coder> coderRepo,
        IGenericRepository<CoderTechnicalSkill> coderTechSkillRepo,
        IGenericRepository<TechnicalSkill> techSkillRepo,
        IGenericRepository<CoderSoftSkill> coderSoftSkillRepo,
        IGenericRepository<SoftSkill> softSkillRepo,
        IGenericRepository<ProfessionalProfile> profileRepo,
        IGenericRepository<ClanCoder> clanCoderRepo,
        IGenericRepository<Clan> clanRepo)
    {
        _coderRepo = coderRepo;
        _coderTechSkillRepo = coderTechSkillRepo;
        _techSkillRepo = techSkillRepo;
        _coderSoftSkillRepo = coderSoftSkillRepo;
        _softSkillRepo = softSkillRepo;
        _profileRepo = profileRepo;
        _clanCoderRepo = clanCoderRepo;
        _clanRepo = clanRepo;
    }

    public async Task<CvResponseDto> GenerateCvAsync(int coderId)
    {
        var coder = await _coderRepo.GetByIdAsync(coderId);
        if (coder == null) throw new KeyNotFoundException($"Coder {coderId} not found");

        // Fetch related data
        var profile = await _profileRepo.GetByIdAsync(coder.ProfessionalProfileId);
        
        var coderTechSkills = await _coderTechSkillRepo.FindAsync(x => x.CoderId == coderId);
        var techSkills = new List<string>();
        foreach(var cts in coderTechSkills)
        {
            var skill = await _techSkillRepo.GetByIdAsync(cts.SkillId);
            if(skill != null) techSkills.Add($"{skill.Name} ({cts.Level})");
        }

        var coderSoftSkills = await _coderSoftSkillRepo.FindAsync(x => x.CoderId == coderId);
        var softSkills = new List<string>();
        foreach(var css in coderSoftSkills)
        {
            var skill = await _softSkillRepo.GetByIdAsync(css.SoftSkillId);
            if(skill != null) softSkills.Add(skill.Name);
        }

        var clanCoders = await _clanCoderRepo.FindAsync(x => x.CoderId == coderId);
        var clans = new List<string>();
        foreach(var cc in clanCoders)
        {
            var clan = await _clanRepo.GetByIdAsync(cc.ClanId);
            if(clan != null) clans.Add(clan.Name);
        }

        // Generate Mock AI Content
        var sb = new StringBuilder();
        sb.AppendLine($"# Curriculum Vitae: {coder.FullName}");
        sb.AppendLine($"**Generated by RiwiLens AI**");
        sb.AppendLine();
        
        sb.AppendLine("## Personal Information");
        sb.AppendLine($"- **Email:** {coder.UserId} (System ID)"); // Assuming UserId maps to email or similar in real scenario
        sb.AppendLine($"- **Location:** {coder.City}, {coder.Country}");
        sb.AppendLine($"- **Address:** {coder.Address}");
        sb.AppendLine();

        if (profile != null)
        {
            sb.AppendLine("## Professional Profile");
            sb.AppendLine(profile.AboutMe);
            sb.AppendLine();
            sb.AppendLine("### Links");
            if(!string.IsNullOrEmpty(profile.LinkedIn)) sb.AppendLine($"- [LinkedIn]({profile.LinkedIn})");
            if(!string.IsNullOrEmpty(profile.GitHub)) sb.AppendLine($"- [GitHub]({profile.GitHub})");
            if(!string.IsNullOrEmpty(profile.Portfolio)) sb.AppendLine($"- [Portfolio]({profile.Portfolio})");
            sb.AppendLine();
        }

        sb.AppendLine("## Technical Skills");
        if (techSkills.Any())
        {
            foreach (var skill in techSkills) sb.AppendLine($"- {skill}");
        }
        else
        {
            sb.AppendLine("No technical skills recorded.");
        }
        sb.AppendLine();

        sb.AppendLine("## Soft Skills");
        if (softSkills.Any())
        {
            foreach (var skill in softSkills) sb.AppendLine($"- {skill}");
        }
        else
        {
            sb.AppendLine("No soft skills recorded.");
        }
        sb.AppendLine();

        sb.AppendLine("## Clan History");
        if (clans.Any())
        {
            foreach (var clan in clans) sb.AppendLine($"- {clan}");
        }
        else
        {
            sb.AppendLine("No clan history.");
        }

        return new CvResponseDto
        {
            CoderId = coder.Id,
            FullName = coder.FullName,
            CvContent = sb.ToString(),
            GeneratedAt = DateTime.UtcNow
        };
    }
}
